//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_medico
    {
        public int id_persona { get; set; }
        public int id_medico { get; set; }
        public string Nombre_Completo { get; set; }
        public string Rut { get; set; }
        public string Cargo_Medico { get; set; }
        public decimal Telefono { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
    }
}
