//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOJA_ATENCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOJA_ATENCION()
        {
            this.RECETA_MEDICAMENTO = new HashSet<RECETA_MEDICAMENTO>();
        }
    
        public int id_hoja { get; set; }
        public System.DateTime ingreso { get; set; }
        public string observacion { get; set; }
        public string receta { get; set; }
        public int id_paciente { get; set; }
        public int id_med { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA_MEDICAMENTO> RECETA_MEDICAMENTO { get; set; }
    }
}
