//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICO()
        {
            this.HOJA_ATENCION = new HashSet<HOJA_ATENCION>();
        }
    
        public int id_med { get; set; }
        public string cargo_med { get; set; }
        public int id_persona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOJA_ATENCION> HOJA_ATENCION { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
