//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int id_reserva { get; set; }
        public int cantidad { get; set; }
        public int id_paciente { get; set; }
        public int id_medica { get; set; }
    
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
