//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaCesfam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_medicamentos
    {
        public int id_medica { get; set; }
        public int Stock_medicamento { get; set; }
        public Nullable<int> Reservado { get; set; }
        public Nullable<int> Restante { get; set; }
        public string Nombre_Medicamento { get; set; }
    }
}
